// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSPrimaryRay
#pragma kernel CSAmbientOcclusion
#pragma kernel CSDiffuseRay

#include "SDFs.hlsl"
#include "RayHit.hlsl"
#include "Lighting.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> colorTex;
RWTexture2D<float4> depthTex;

uniform float4 ScreenSize;
uniform float4x4 CamToWorld;

uniform float MinClip;
uniform float MaxClip;
uniform float FOV_Tan;

uniform float quality;
uniform int maxSteps = 400;
uniform float secQuality;
uniform int secMaxSteps = 50;

static float PI = 3.14159;

float3 GetViewDir(int2 id)
{
    //normalized [-1,1]
    float2 uv = ((float2) id.xy) * ScreenSize.zw * 2.0 - 1;
    uv.x *= ScreenSize.x * ScreenSize.w;
    //Sampling a Sphere
    float3 rayDir = normalize(float3(uv * FOV_Tan, 1.0));
    return mul((float3x3) CamToWorld, rayDir);
}

[numthreads(8,8,1)]
void CSPrimaryRay(uint3 id : SV_DispatchThreadID)
{
    float3 rayDir = GetViewDir(id.xy);
    float3 camPos = CamToWorld._14_24_34;

    //Cone tracing, how large is pixel relative to screen
    float cutoff = .001 * quality;
    float dist = MinClip, distToScene;
    float3 pos = camPos + rayDir * dist;
    for (int i = 0; i < maxSteps; i++)
    {
        distToScene = SDF(pos) * quality;
        dist += distToScene;
        //This should converge slightly better
        pos = rayDir * dist + camPos;
        
        //use ABS to better converge for fractal geometries
        if (abs(distToScene) < max(cutoff * dist, cutoff))
            break;
        if (dist > MaxClip)
            break;
    }
    
    float3 normal = GetNormal(pos);
    depthTex[id.xy] = float4(normal, dist);
    colorTex[id.xy] = float4(CalculateLighting(pos, rayDir, normal, dist), 1.0);
    rayHit hit;
    hit.depth = dist;
    hit.normal = normal;
    hit.pixelID = id.x + id.y * ScreenSize.x;
    hit.position = pos;
    hitBufferRW[id.x + ScreenSize.x * id.y] = hit;
}

static const float3 AOKernel[32] =
{
    RNGHemisphere(1) * 0.125, RNGHemisphere(2) * 0.125, RNGHemisphere(3) * 0.125, RNGHemisphere(4) * 0.125,
    RNGHemisphere(5) * 0.125, RNGHemisphere(6) * 0.125, RNGHemisphere(7) * 0.125, RNGHemisphere(8) * 0.125,
    RNGHemisphere(9) * 0.250, RNGHemisphere(10) * 0.250, RNGHemisphere(11) * 0.250, RNGHemisphere(12) * 0.250,
    RNGHemisphere(13) * 0.250, RNGHemisphere(14) * 0.250, RNGHemisphere(15) * 0.250, RNGHemisphere(16) * 0.250,
    RNGHemisphere(17) * 0.500, RNGHemisphere(18) * 0.500, RNGHemisphere(19) * 0.500, RNGHemisphere(20) * 0.500,
    RNGHemisphere(21) * 0.500, RNGHemisphere(22) * 0.500, RNGHemisphere(23) * 0.500, RNGHemisphere(24) * 0.500,
    RNGHemisphere(25) * 1.000, RNGHemisphere(26) * 1.000, RNGHemisphere(27) * 1.000, RNGHemisphere(28) * 1.000,
    RNGHemisphere(29) * 1.000, RNGHemisphere(30) * 1.000, RNGHemisphere(31) * 1.000, RNGHemisphere(32) * 1.000,
};
[numthreads(16, 16, 1)]
void CSAmbientOcclusion(uint3 id : SV_DispatchThreadID)
{
    float3 pos = depthTex[id.xy].a * GetViewDir(id.xy) + CamToWorld._14_24_34;
    float3 normal = depthTex[id.xy].rgb;
    float3x3 basis = GetBasis(normal);

    float occlusion = 0.0;
    
    for (int i = 24; i < 32; i++)
    {
        float3 samplePos = pos + mul(basis, AOKernel[i]);
        float t = SDF(samplePos);
        occlusion += saturate(t / 1.000);
    }
    occlusion /= 2;
    for (i = 16; i < 24; i++)
    {
        float3 samplePos = pos + mul(basis, AOKernel[i]);
        float t = SDF(samplePos);
        occlusion += saturate(t / 0.500);
    }
    occlusion /= 2;
    for (i = 8; i < 16; i++)
    {
        float3 samplePos = pos + mul(basis, AOKernel[i]);
        float t = SDF(samplePos);
        occlusion += saturate(t / 0.250);
    }
    occlusion /= 2;
    for (i = 0; i < 8; i++)
    {
        float3 samplePos = pos + mul(basis, AOKernel[i]);
        float t = SDF(samplePos);
        occlusion += saturate(t / 0.125);
    }
    occlusion /= 2;

    float3 emission = colorTex[id.xy].xyz;
    emission *= occlusion;
    colorTex[id.xy] = float4(emission, 1);
}


//Diffuse only need 1 bounce
[numthreads(8, 8, 1)]
void CSDiffuseRay(uint3 id : SV_DispatchThreadID)
{
    rayHit hit = hitBuffer[id.x + ScreenSize.x * id.y];
    if (hit.pixelID == -1)
        return;
    
    float3 origin = hit.position;
    float3x3 basis = GetBasis(origin);
    float3 color = GetSurfaceColor(origin);
    float3 finColor = float3(0, 0, 0);
    
    //Basically Copy Paste
    int sampleCount = 64;
    for (int z = 0; z < sampleCount; z++)
    {
        float3 rayDir = RNGCosHemisphere(z * 4096 * 4096);
        rayDir = mul(basis, rayDir);
        
        float cutoff = .01;
        float dist = 1.0, distToScene = 0;
        float3 pos = origin + rayDir; //Start far from the SDF, so you dont get stuck in it
        for (int i = 0; i < 20; i++) //40 is enough to converge for most scenes
        {
            pos = origin + rayDir * dist;
            distToScene = SDF(pos);
            dist += distToScene;
        
            if (abs(distToScene) < max(cutoff * dist, cutoff))
                break;
            if (dist > MaxClip)
                break;
        }
        
        finColor += CalculateLighting(pos, rayDir, GetNormal(pos), dist);
    }
    
    finColor *= color / float(sampleCount);
    finColor = finColor + colorTex[id.xy].rgb;
    colorTex[id.xy] = float4(finColor, 1.0);

}
