// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSPrimaryRay
#pragma kernel CSAmbientOcclusion
#pragma kernel CSDiffuseRay

#include "SDFs.hlsl"
#include "RayHit.hlsl"
#include "Lighting.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> colorTex;
RWTexture2D<float4> depthTex;

uniform float4 ScreenSize;
uniform float4x4 CamToWorld;

uniform float MinClip;
uniform float MaxClip;
uniform float FOV_Tan;

uniform float quality;
uniform int maxSteps = 400;
uniform float secQuality;
uniform int secMaxSteps = 50;

static float PI = 3.14159;

float3 GetViewDir(int2 id)
{
    //normalized [-1,1]
    float2 uv = ((float2) id.xy) * ScreenSize.zw * 2.0 - 1;
    uv.x *= ScreenSize.x * ScreenSize.w;
    //Sampling a Sphere
    float3 rayDir = normalize(float3(uv * FOV_Tan, 1.0));
    return mul((float3x3) CamToWorld, rayDir);
}

[numthreads(8,8,1)]
void CSPrimaryRay(uint3 id : SV_DispatchThreadID)
{
    float3 rayDir = GetViewDir(id.xy);
    float3 camPos = CamToWorld._14_24_34;

    //Cone tracing, how large is pixel relative to screen
    float cutoff = .001 * quality;
    float dist = MinClip, distToScene;
    float3 pos = camPos + rayDir * dist;
    for (int i = 0; i < maxSteps; i++)
    {
        distToScene = SDF(pos) * quality;
        dist += distToScene;
        //This should converge slightly better
        pos = rayDir * dist + camPos;
        
        //use ABS to better converge for fractal geometries
        if (abs(distToScene) < max(cutoff * dist, cutoff))
            break;
        if (dist > MaxClip)
            break;
    }
    
    float3 normal = GetNormal(pos);
    depthTex[id.xy] = float4(normal, dist);
    colorTex[id.xy] = float4(CalculateLighting(pos, rayDir, normal, dist), 1.0);
    rayHit hit;
    hit.depth = dist;
    hit.normal = normal;
    hit.pixelID = id.x + id.y * ScreenSize.x;
    hit.position = pos;
    hitBufferRW[id.x + ScreenSize.x * id.y] = hit;
}

static const float AOScale[4] = { 0.125, 0.250, 0.500, 1.000 };
static const float3 AOKernel[32] =
{
    RNGHemisphere(1) * AOScale[0], RNGHemisphere(2) * AOScale[0], RNGHemisphere(3) * AOScale[0], RNGHemisphere(4) * AOScale[0],
    RNGHemisphere(5) * AOScale[0], RNGHemisphere(6) * AOScale[0], RNGHemisphere(7) * AOScale[0], RNGHemisphere(8) * AOScale[0],
    RNGHemisphere(9) * AOScale[1], RNGHemisphere(10) * AOScale[1], RNGHemisphere(11) * AOScale[1], RNGHemisphere(12) * AOScale[1],
    RNGHemisphere(13) * AOScale[1], RNGHemisphere(14) * AOScale[1], RNGHemisphere(15) * AOScale[1], RNGHemisphere(16) * AOScale[1],
    RNGHemisphere(17) * AOScale[2], RNGHemisphere(18) * AOScale[2], RNGHemisphere(19) * AOScale[2], RNGHemisphere(20) * AOScale[2],
    RNGHemisphere(21) * AOScale[2], RNGHemisphere(22) * AOScale[2], RNGHemisphere(23) * AOScale[2], RNGHemisphere(24) * AOScale[2],
    RNGHemisphere(25) * AOScale[3], RNGHemisphere(26) * AOScale[3], RNGHemisphere(27) * AOScale[3], RNGHemisphere(28) * AOScale[3],
    RNGHemisphere(29) * AOScale[3], RNGHemisphere(30) * AOScale[3], RNGHemisphere(31) * AOScale[3], RNGHemisphere(32) * AOScale[3],
};
[numthreads(16, 16, 1)]
void CSAmbientOcclusion(uint3 id : SV_DispatchThreadID)
{
    float3 pos = depthTex[id.xy].a * GetViewDir(id.xy) + CamToWorld._14_24_34;
    float3 normal = depthTex[id.xy].rgb;
    float3x3 basis = GetBasis(normal);

    float occlusion = 0.0;
    
    for (int i = 24; i < 32; i++)
    {
        float3 samplePos = pos + mul(AOKernel[i], basis);
        float t = SDF(samplePos);
        occlusion += saturate(t / AOScale[3]);
    }
    occlusion /= 2;
    for (i = 16; i < 24; i++)
    {
        float3 samplePos = pos + mul(AOKernel[i], basis);
        float t = SDF(samplePos);
        occlusion += saturate(t / AOScale[2]);
    }
    occlusion /= 4;
    for (i = 8; i < 16; i++)
    {
        float3 samplePos = pos + mul(AOKernel[i], basis);
        float t = SDF(samplePos);
        occlusion += saturate(t / AOScale[1]);
    }
    occlusion /= 6;
    for (i = 0; i < 8; i++)
    {
        float3 samplePos = pos + mul(AOKernel[i], basis);
        float t = SDF(samplePos);
        occlusion += saturate(t / AOScale[0]);
    }
    occlusion /= 8;

    float3 emission = colorTex[id.xy].xyz;
    emission *= occlusion;
    colorTex[id.xy] = float4(emission, 1);
}

static const float3 DKernel[128] =
{
    RNGCosHemisphere(0), RNGCosHemisphere(1), RNGCosHemisphere(2), RNGCosHemisphere(3),
    RNGCosHemisphere(4), RNGCosHemisphere(5), RNGCosHemisphere(6), RNGCosHemisphere(7),
    RNGCosHemisphere(8), RNGCosHemisphere(9), RNGCosHemisphere(10), RNGCosHemisphere(11),
    RNGCosHemisphere(12), RNGCosHemisphere(13), RNGCosHemisphere(14), RNGCosHemisphere(15),

    RNGCosHemisphere(16), RNGCosHemisphere(17), RNGCosHemisphere(18), RNGCosHemisphere(19),
    RNGCosHemisphere(20), RNGCosHemisphere(21), RNGCosHemisphere(22), RNGCosHemisphere(23),
    RNGCosHemisphere(24), RNGCosHemisphere(25), RNGCosHemisphere(26), RNGCosHemisphere(27),
    RNGCosHemisphere(28), RNGCosHemisphere(29), RNGCosHemisphere(30), RNGCosHemisphere(31),

    RNGCosHemisphere(32), RNGCosHemisphere(33), RNGCosHemisphere(34), RNGCosHemisphere(35),
    RNGCosHemisphere(36), RNGCosHemisphere(37), RNGCosHemisphere(38), RNGCosHemisphere(39),
    RNGCosHemisphere(40), RNGCosHemisphere(41), RNGCosHemisphere(42), RNGCosHemisphere(43),
    RNGCosHemisphere(44), RNGCosHemisphere(45), RNGCosHemisphere(46), RNGCosHemisphere(47),

    RNGCosHemisphere(48), RNGCosHemisphere(49), RNGCosHemisphere(50), RNGCosHemisphere(51),
    RNGCosHemisphere(52), RNGCosHemisphere(53), RNGCosHemisphere(54), RNGCosHemisphere(55),
    RNGCosHemisphere(56), RNGCosHemisphere(57), RNGCosHemisphere(58), RNGCosHemisphere(59),
    RNGCosHemisphere(60), RNGCosHemisphere(61), RNGCosHemisphere(62), RNGCosHemisphere(63),

    RNGCosHemisphere(64), RNGCosHemisphere(65), RNGCosHemisphere(66), RNGCosHemisphere(67),
    RNGCosHemisphere(68), RNGCosHemisphere(69), RNGCosHemisphere(70), RNGCosHemisphere(71),
    RNGCosHemisphere(72), RNGCosHemisphere(73), RNGCosHemisphere(74), RNGCosHemisphere(75),
    RNGCosHemisphere(76), RNGCosHemisphere(77), RNGCosHemisphere(78), RNGCosHemisphere(79),

    RNGCosHemisphere(80), RNGCosHemisphere(81), RNGCosHemisphere(82), RNGCosHemisphere(83),
    RNGCosHemisphere(84), RNGCosHemisphere(85), RNGCosHemisphere(86), RNGCosHemisphere(87),
    RNGCosHemisphere(88), RNGCosHemisphere(89), RNGCosHemisphere(90), RNGCosHemisphere(91),
    RNGCosHemisphere(92), RNGCosHemisphere(93), RNGCosHemisphere(94), RNGCosHemisphere(95),

    RNGCosHemisphere(96), RNGCosHemisphere(97), RNGCosHemisphere(98), RNGCosHemisphere(99),
    RNGCosHemisphere(100), RNGCosHemisphere(101), RNGCosHemisphere(102), RNGCosHemisphere(103),
    RNGCosHemisphere(104), RNGCosHemisphere(105), RNGCosHemisphere(106), RNGCosHemisphere(107),
    RNGCosHemisphere(108), RNGCosHemisphere(109), RNGCosHemisphere(110), RNGCosHemisphere(111),

    RNGCosHemisphere(112), RNGCosHemisphere(113), RNGCosHemisphere(114), RNGCosHemisphere(115),
    RNGCosHemisphere(116), RNGCosHemisphere(117), RNGCosHemisphere(118), RNGCosHemisphere(119),
    RNGCosHemisphere(120), RNGCosHemisphere(121), RNGCosHemisphere(122), RNGCosHemisphere(123),
    RNGCosHemisphere(124), RNGCosHemisphere(125), RNGCosHemisphere(126), RNGCosHemisphere(127),
};

//Diffuse only need 1 bounce
[numthreads(8, 8, 1)]
void CSDiffuseRay(uint3 id : SV_DispatchThreadID)
{
    rayHit hit = hitBuffer[id.x + ScreenSize.x * id.y];
    if (hit.pixelID == -1)
        return;
    
    float3 origin = hit.position;
    float3x3 basis = GetBasis(hit.normal);
    float3 color = GetSurfaceColor(origin, GetNormal(origin));
    float3 finColor = float3(0, 0, 0);
    
    //This should be Adjustable
    float a = 32.0;
    float b = 4.0;
    float s = 2.0;
    
    //Basically Copy Paste
    int sampleCount = b + (a - b) / (1 + (hit.depth * hit.depth / s / s));
    //int sampleCount = a;
    int hitCount = 0;
    for (int z = 0; z < sampleCount; z++)
    {
        float3 rayDir = mul(basis, DKernel[z]);
        
        float cutoff = .1;
        float dist = 1.0, distToScene = dist;
        float3 pos = origin + rayDir * dist; //Start far from the SDF, so you dont get stuck in it
        //Trying to make a tight loop
        for (int i = 0; i < 28; i++)
        {
            pos = origin + rayDir * dist;
            distToScene = SDF(pos);
            dist += distToScene;
            
            if (abs(distToScene) < cutoff)
                break;
        }
        if (abs(distToScene) < cutoff)
        {
            finColor += CalculateLighting(pos, rayDir, hit.normal, dist);
            hitCount += 1;
        }
    }
    
    finColor /= float(hitCount);
    finColor /= (hit.depth * hit.depth + 1);
    finColor = finColor + colorTex[id.xy].rgb;
    colorTex[id.xy] = float4(finColor, 1.0);
}
